apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-latency-collecter
  namespace: default
  labels:
    k8s-app: k8s-latency-collecter
spec:
  selector:
    matchLabels:
      k8s-app: k8s-latency-collecter
  template:
    metadata:
      labels:
        k8s-app: k8s-latency-collecter
    spec:
      containers:
      - image: "leta101/k8s-latency-collecter:latest"
        name: k8s-latency-collecter
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 50m
            memory: 100Mi
        ports:
    # port is must be 9400
        - containerPort: 9400
          hostPort: 9400
          protocol: TCP
  updateStrategy:
    type: RollingUpdate
